// Code generated by FHIR Generator. DO NOT EDIT.
// Defines organization behavior of a group.
package fhir_r4b_go
// ActionGroupingBehavior represents the FHIR ValueSet as an enumeration
type ActionGroupingBehavior struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	ActionGroupingBehavior_Visual_group = "visual-group" // Visual Group: Any group marked with this behavior should be displayed as a visual group to the end user.
	ActionGroupingBehavior_Logical_group = "logical-group" // Logical Group: A group with this behavior logically groups its sub-elements, and may be shown as a visual group to the end user, but it is not required to do so.
	ActionGroupingBehavior_Sentence_group = "sentence-group" // Sentence Group: A group of related alternative actions is a sentence group if the target referenced by the action is the same in all the actions and each action simply constitutes a different variation on how to specify the details for the target. For example, two actions that could be in a SentenceGroup are "aspirin, 500 mg, 2 times per day" and "aspirin, 300 mg, 3 times per day". In both cases, aspirin is the target referenced by the action, and the two actions represent different options for how aspirin might be ordered for the patient. Note that a SentenceGroup would almost always have an associated selection behavior of "AtMostOne", unless it's a required action, in which case, it would be "ExactlyOne".
)

// Clone creates a deep copy of the enum
func (e ActionGroupingBehavior) Clone() *ActionGroupingBehavior {
	return &ActionGroupingBehavior{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *ActionGroupingBehavior) Equals(other *ActionGroupingBehavior) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

