// Code generated by FHIR Generator. DO NOT EDIT.
// Defines expectations around whether an action or action group is required.
package fhir_r4b_go
// ActionRequiredBehavior represents the FHIR ValueSet as an enumeration
type ActionRequiredBehavior struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	ActionRequiredBehavior_Must = "must" // Must: An action with this behavior must be included in the actions processed by the end user; the end user SHALL NOT choose not to include this action.
	ActionRequiredBehavior_Could = "could" // Could: An action with this behavior may be included in the set of actions processed by the end user.
	ActionRequiredBehavior_Must_unless_documented = "must-unless-documented" // Must Unless Documented: An action with this behavior must be included in the set of actions processed by the end user, unless the end user provides documentation as to why the action was not included.
)

// Clone creates a deep copy of the enum
func (e ActionRequiredBehavior) Clone() *ActionRequiredBehavior {
	return &ActionRequiredBehavior{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *ActionRequiredBehavior) Equals(other *ActionRequiredBehavior) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

