// Code generated by FHIR Generator. DO NOT EDIT.
// Identification of the underlying physiological mechanism for a Reaction Risk.
package fhir_r4b_go
// AllergyIntoleranceType represents the FHIR ValueSet as an enumeration
type AllergyIntoleranceType struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	AllergyIntoleranceType_Allergy = "allergy" // Allergy: A propensity for hypersensitive reaction(s) to a substance. These reactions are most typically type I hypersensitivity, plus other "allergy-like" reactions, including pseudoallergy.
	AllergyIntoleranceType_Intolerance = "intolerance" // Intolerance: A propensity for adverse reactions to a substance that is not judged to be allergic or "allergy-like". These reactions are typically (but not necessarily) non-immune. They are to some degree idiosyncratic and/or patient-specific (i.e. are not a reaction that is expected to occur with most or all patients given similar circumstances).
)

// Clone creates a deep copy of the enum
func (e AllergyIntoleranceType) Clone() *AllergyIntoleranceType {
	return &AllergyIntoleranceType{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *AllergyIntoleranceType) Equals(other *AllergyIntoleranceType) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

