// Code generated by FHIR Generator. DO NOT EDIT.
// Category of an identified substance associated with allergies or intolerances.
package fhir_r4b_go

// AllergyIntoleranceCategory represents the FHIR ValueSet as an enumeration
type AllergyIntoleranceCategory int

const (
	// Food: Any substance consumed to provide nutritional support for the body.
	AllergyIntoleranceCategory_Food AllergyIntoleranceCategory = iota
	// Medication: Substances administered to achieve a physiological effect.
	AllergyIntoleranceCategory_Medication AllergyIntoleranceCategory = iota
	// Environment: Any substances that are encountered in the environment, including any substance not already classified as food, medication, or biologic.
	AllergyIntoleranceCategory_Environment AllergyIntoleranceCategory = iota
	// Biologic: A preparation that is synthesized from living organisms or their products, especially a human or animal protein, such as a hormone or antitoxin, that is used as a diagnostic, preventive, or therapeutic agent. Examples of biologic medications include: vaccines; allergenic extracts, which are used for both diagnosis and treatment (for example, allergy shots); gene therapies; cellular therapies. There are other biologic products, such as tissues, which are not typically associated with allergies.
	AllergyIntoleranceCategory_Biologic AllergyIntoleranceCategory = iota
)

// String converts the enum to its string representation
func (e AllergyIntoleranceCategory) String() string {
	switch e {
	case AllergyIntoleranceCategory_Food: return "Food"
	case AllergyIntoleranceCategory_Medication: return "Medication"
	case AllergyIntoleranceCategory_Environment: return "Environment"
	case AllergyIntoleranceCategory_Biologic: return "Biologic"
	default: return "Unknown"
	}
}

