// Code generated by FHIR Generator. DO NOT EDIT.
// Identification of the underlying physiological mechanism for a Reaction Risk.
package fhir_r4b_go

// AllergyIntoleranceType represents the FHIR ValueSet as an enumeration
type AllergyIntoleranceType int

const (
	// Allergy: A propensity for hypersensitive reaction(s) to a substance. These reactions are most typically type I hypersensitivity, plus other "allergy-like" reactions, including pseudoallergy.
	AllergyIntoleranceType_Allergy AllergyIntoleranceType = iota
	// Intolerance: A propensity for adverse reactions to a substance that is not judged to be allergic or "allergy-like". These reactions are typically (but not necessarily) non-immune. They are to some degree idiosyncratic and/or patient-specific (i.e. are not a reaction that is expected to occur with most or all patients given similar circumstances).
	AllergyIntoleranceType_Intolerance AllergyIntoleranceType = iota
)

// String converts the enum to its string representation
func (e AllergyIntoleranceType) String() string {
	switch e {
	case AllergyIntoleranceType_Allergy: return "Allergy"
	case AllergyIntoleranceType_Intolerance: return "Intolerance"
	default: return "Unknown"
	}
}

