// Code generated by FHIR Generator. DO NOT EDIT.
// The free/busy status of an appointment.
package fhir_r4b_go
// AppointmentStatus represents the FHIR ValueSet as an enumeration
type AppointmentStatus struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	AppointmentStatus_Proposed = "proposed" // Proposed: None of the participant(s) have finalized their acceptance of the appointment request, and the start/end time might not be set yet.
	AppointmentStatus_Pending = "pending" // Pending: Some or all of the participant(s) have not finalized their acceptance of the appointment request.
	AppointmentStatus_Booked = "booked" // Booked: All participant(s) have been considered and the appointment is confirmed to go ahead at the date/times specified.
	AppointmentStatus_Arrived = "arrived" // Arrived: The patient/patients has/have arrived and is/are waiting to be seen.
	AppointmentStatus_Fulfilled = "fulfilled" // Fulfilled: The planning stages of the appointment are now complete, the encounter resource will exist and will track further status changes. Note that an encounter may exist before the appointment status is fulfilled for many reasons.
	AppointmentStatus_Cancelled = "cancelled" // Cancelled: The appointment has been cancelled.
	AppointmentStatus_Noshow = "noshow" // No Show: Some or all of the participant(s) have not/did not appear for the appointment (usually the patient).
	AppointmentStatus_Entered_in_error = "entered-in-error" // Entered in error: This instance should not have been part of this patient's medical record.
	AppointmentStatus_Checked_in = "checked-in" // Checked In: When checked in, all pre-encounter administrative work is complete, and the encounter may begin. (where multiple patients are involved, they are all present).
	AppointmentStatus_Waitlist = "waitlist" // Waitlisted: The appointment has been placed on a waitlist, to be scheduled/confirmed in the future when a slot/service is available. A specific time might or might not be pre-allocated.
)

// Clone creates a deep copy of the enum
func (e AppointmentStatus) Clone() *AppointmentStatus {
	return &AppointmentStatus{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *AppointmentStatus) Equals(other *AppointmentStatus) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

