// Code generated by FHIR Generator. DO NOT EDIT.
// The type of relations between entries.
package fhir_r4b_go

// CatalogEntryRelationType represents the FHIR ValueSet as an enumeration
type CatalogEntryRelationType int

const (
	// Triggers: the related entry represents an activity that may be triggered by the current item.
	CatalogEntryRelationType_Triggers CatalogEntryRelationType = iota
	// Replaced By: the related entry represents an item that replaces the current retired item.
	CatalogEntryRelationType_Is_replaced_by CatalogEntryRelationType = iota
)

// String converts the enum to its string representation
func (e CatalogEntryRelationType) String() string {
	switch e {
	case CatalogEntryRelationType_Triggers: return "Triggers"
	case CatalogEntryRelationType_Is_replaced_by: return "Replaced By"
	default: return "Unknown"
	}
}

