// Code generated by FHIR Generator. DO NOT EDIT.
// The method used to determine the characteristic(s) of the variable.
package fhir_r4b_go
// CharacteristicMethod represents the FHIR ValueSet as an enumeration
type CharacteristicMethod struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	CharacteristicMethod_Default = "Default" // Default: Default.
)

// Clone creates a deep copy of the enum
func (e CharacteristicMethod) Clone() *CharacteristicMethod {
	return &CharacteristicMethod{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *CharacteristicMethod) Equals(other *CharacteristicMethod) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

