// Code generated by FHIR Generator. DO NOT EDIT.
// Cited Artifact Classification Type
package fhir_r4b_go

// CitedArtifactClassificationType represents the FHIR ValueSet as an enumeration
type CitedArtifactClassificationType int

const (
	// Publication type: Publication type
	CitedArtifactClassificationType_Publication_type CitedArtifactClassificationType = iota
	// MeSH heading: MeSH heading
	CitedArtifactClassificationType_Mesh_heading CitedArtifactClassificationType = iota
	// Supplemental MeSH for Protocol: Supplemental MeSH for Protocol
	CitedArtifactClassificationType_Supplemental_mesh_protocol CitedArtifactClassificationType = iota
	// Supplemental MeSH for Disease: Supplemental MeSH for Disease
	CitedArtifactClassificationType_Supplemental_mesh_disease CitedArtifactClassificationType = iota
	// Supplemental MeSH for Organism: Supplemental MeSH for Organism
	CitedArtifactClassificationType_Supplemental_mesh_organism CitedArtifactClassificationType = iota
	// Keyword: Keyword
	CitedArtifactClassificationType_Keyword CitedArtifactClassificationType = iota
	// Citation subset: Citation subset
	CitedArtifactClassificationType_Citation_subset CitedArtifactClassificationType = iota
	// Chemical: Chemical
	CitedArtifactClassificationType_Chemical CitedArtifactClassificationType = iota
	// Publishing Model: Used for PubModel attribute in Medline
	CitedArtifactClassificationType_Publishing_model CitedArtifactClassificationType = iota
	// Knowledge Artifact Type: Knowledge Artifact Type
	CitedArtifactClassificationType_Knowledge_artifact_type CitedArtifactClassificationType = iota
	// Coverage: The spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant
	CitedArtifactClassificationType_Coverage CitedArtifactClassificationType = iota
)

// String converts the enum to its string representation
func (e CitedArtifactClassificationType) String() string {
	switch e {
	case CitedArtifactClassificationType_Publication_type: return "Publication type"
	case CitedArtifactClassificationType_Mesh_heading: return "MeSH heading"
	case CitedArtifactClassificationType_Supplemental_mesh_protocol: return "Supplemental MeSH for Protocol"
	case CitedArtifactClassificationType_Supplemental_mesh_disease: return "Supplemental MeSH for Disease"
	case CitedArtifactClassificationType_Supplemental_mesh_organism: return "Supplemental MeSH for Organism"
	case CitedArtifactClassificationType_Keyword: return "Keyword"
	case CitedArtifactClassificationType_Citation_subset: return "Citation subset"
	case CitedArtifactClassificationType_Chemical: return "Chemical"
	case CitedArtifactClassificationType_Publishing_model: return "Publishing Model"
	case CitedArtifactClassificationType_Knowledge_artifact_type: return "Knowledge Artifact Type"
	case CitedArtifactClassificationType_Coverage: return "Coverage"
	default: return "Unknown"
	}
}

