// Code generated by FHIR Generator. DO NOT EDIT.
// A categorisation for a clinical use information item.
package fhir_r4b_go

// ClinicalUseDefinitionCategory represents the FHIR ValueSet as an enumeration
type ClinicalUseDefinitionCategory int

const (
	// Pregnancy and Lactation: 
	ClinicalUseDefinitionCategory_Pregnancy ClinicalUseDefinitionCategory = iota
	// Overdose: 
	ClinicalUseDefinitionCategory_Overdose ClinicalUseDefinitionCategory = iota
	// Effects on Ability to Drive and Use Machines: 
	ClinicalUseDefinitionCategory_DriveAndMachines ClinicalUseDefinitionCategory = iota
)

// String converts the enum to its string representation
func (e ClinicalUseDefinitionCategory) String() string {
	switch e {
	case ClinicalUseDefinitionCategory_Pregnancy: return "Pregnancy and Lactation"
	case ClinicalUseDefinitionCategory_Overdose: return "Overdose"
	case ClinicalUseDefinitionCategory_DriveAndMachines: return "Effects on Ability to Drive and Use Machines"
	default: return "Unknown"
	}
}

