// Code generated by FHIR Generator. DO NOT EDIT.
// Dose forms for a product as a whole, considering all individual parts, but before any mixing
package fhir_r4b_go
// CombinedDoseForm represents the FHIR ValueSet as an enumeration
type CombinedDoseForm struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	CombinedDoseForm_Value100000073366 = "100000073366" // Powder and solvent for oral solution: 
	CombinedDoseForm_Value100000073651 = "100000073651" // Powder and solvent for oral suspension: 
	CombinedDoseForm_Value100000073774 = "100000073774" // Eye drops, powder and solvent for solution: 
	CombinedDoseForm_Value100000073781 = "100000073781" // Eye drops, powder and solvent for suspension: 
	CombinedDoseForm_Value100000073801 = "100000073801" // Ear drops, powder and solvent for suspension: 
	CombinedDoseForm_Value100000073860 = "100000073860" // Powder and solvent for solution for infusion: 
	CombinedDoseForm_Value100000073868 = "100000073868" // Powder and solvent for solution for injection: 
	CombinedDoseForm_Value100000073869 = "100000073869" // Powder and solvent for suspension for injection: 
	CombinedDoseForm_Value100000073884 = "100000073884" // Powder and solvent for implantation paste: 
	CombinedDoseForm_Value100000073891 = "100000073891" // Endotracheopulmonary instillation, powder and solvent for solution: 
	CombinedDoseForm_Value100000073892 = "100000073892" // Powder and solvent for endocervical gel: 
	CombinedDoseForm_Value100000073941 = "100000073941" // Powder and solvent for sealant: 
	CombinedDoseForm_Value100000073972 = "100000073972" // Concentrate and solvent for concentrate for solution for infusion: 
	CombinedDoseForm_Value100000073973 = "100000073973" // Concentrate and solvent for cutaneous use: 
	CombinedDoseForm_Value100000073974 = "100000073974" // Concentrate and solvent for injection: 
	CombinedDoseForm_Value100000073975 = "100000073975" // Concentrate and solvent for solution for infusion: 
	CombinedDoseForm_Value100000073987 = "100000073987" // Concentrate and diluent for solution for infusion: 
	CombinedDoseForm_Value100000073988 = "100000073988" // Concentrate and solvent for cutaneous solution: 
	CombinedDoseForm_Value100000073989 = "100000073989" // Concentrate and solvent for solution for injection: 
	CombinedDoseForm_Value100000073990 = "100000073990" // Concentrate and solvent for suspension for injection: 
	CombinedDoseForm_Value100000073999 = "100000073999" // Granules and solvent for suspension for injection: 
	CombinedDoseForm_Value100000074015 = "100000074015" // Powder and solvent for concentrate for solution for infusion: 
	CombinedDoseForm_Value100000074016 = "100000074016" // Powder and solvent for cutaneous solution: 
	CombinedDoseForm_Value100000074017 = "100000074017" // Powder and solvent for gingival gel: 
	CombinedDoseForm_Value100000074018 = "100000074018" // Powder and solvent for prolonged-release suspension for injection: 
	CombinedDoseForm_Value100000074030 = "100000074030" // Powder and solvent for endosinusial solution: 
	CombinedDoseForm_Value100000074031 = "100000074031" // Powder and solvent for intraocular instillation solution: 
	CombinedDoseForm_Value100000074032 = "100000074032" // Powder and suspension for suspension for injection: 
	CombinedDoseForm_Value100000074048 = "100000074048" // Suspension and effervescent granules for oral suspension: 
	CombinedDoseForm_Value100000074051 = "100000074051" // Tablet and solvent for rectal suspension: 
	CombinedDoseForm_Value100000074053 = "100000074053" // Powder and solvent for dental gel: 
	CombinedDoseForm_Value100000074056 = "100000074056" // Gas and solvent for dispersion for injection/infusion: 
	CombinedDoseForm_Value100000074057 = "100000074057" // Powder and solvent for solution for injection/infusion: 
	CombinedDoseForm_Value100000074061 = "100000074061" // Suspension and solution for spray: 
	CombinedDoseForm_Value100000074064 = "100000074064" // Tablet and powder for oral solution: 
	CombinedDoseForm_Value100000075580 = "100000075580" // Emulsion and suspension for emulsion for injection: 
	CombinedDoseForm_Value100000075584 = "100000075584" // Powder and solvent for dispersion for injection: 
	CombinedDoseForm_Value100000075587 = "100000075587" // Powder for mouth wash: 
	CombinedDoseForm_Value100000116137 = "100000116137" // Lyophilisate and solvent for solution for injection: 
	CombinedDoseForm_Value100000116141 = "100000116141" // Fibrin sealant-powder and solvent for fibrin sealant: 
	CombinedDoseForm_Value100000116155 = "100000116155" // Granules and solvent for oral suspension: 
	CombinedDoseForm_Value100000116160 = "100000116160" // Lyophilisate and solvent for suspension for injection: 
	CombinedDoseForm_Value100000116172 = "100000116172" // Powder and gel for gel: 
	CombinedDoseForm_Value100000116173 = "100000116173" // Powder and solution for solution for injection: 
	CombinedDoseForm_Value100000116174 = "100000116174" // Powder and solvent for epilesional solution: 
	CombinedDoseForm_Value100000116175 = "100000116175" // Powder and solvent for intravesical solution: 
	CombinedDoseForm_Value100000116176 = "100000116176" // Powder and solvent for intravesical suspension: 
	CombinedDoseForm_Value100000116177 = "100000116177" // Powder and solvent for nebuliser solution: 
	CombinedDoseForm_Value100000116179 = "100000116179" // Powder, dispersion and solvent for concentrate for dispersion for infusion: 
	CombinedDoseForm_Value100000125746 = "100000125746" // Powder and solvent for emulsion for injection: 
	CombinedDoseForm_Value100000125747 = "100000125747" // Nasal drops, powder and solvent for solution: 
	CombinedDoseForm_Value100000125777 = "100000125777" // Suspension and solvent for suspension for injection: 
	CombinedDoseForm_Value100000136318 = "100000136318" // Concentrate and solvent for solution for injection/infusion: 
	CombinedDoseForm_Value100000136325 = "100000136325" // Powder and solvent for solution for injection/skin-prick test: 
	CombinedDoseForm_Value100000136558 = "100000136558" // Lyophilisate and solvent for suspension for nasal administration: 
	CombinedDoseForm_Value100000136560 = "100000136560" // Powder and solvent for solution for sealant: 
	CombinedDoseForm_Value100000136907 = "100000136907" // Solution for dispersion for injection/infusion: 
	CombinedDoseForm_Value100000143502 = "100000143502" // Powder and solution for dental cement: 
	CombinedDoseForm_Value100000143546 = "100000143546" // Endotracheopulmonary instillation, powder and solvent for suspension: 
	CombinedDoseForm_Value100000143552 = "100000143552" // Powder, solvent and matrix for implantation matrix: 
	CombinedDoseForm_Value100000156068 = "100000156068" // Nasal drops, lyophilisate and solvent for suspension: 
	CombinedDoseForm_Value100000157796 = "100000157796" // Lyophilisate and suspension for suspension for injection: 
	CombinedDoseForm_Value100000164467 = "100000164467" // Powder for concentrate and solution for solution for infusion: 
	CombinedDoseForm_Value100000169997 = "100000169997" // Powder and solution for bee-hive solution: 
	CombinedDoseForm_Value100000170588 = "100000170588" // Suspension and solvent for oral spray: 
	CombinedDoseForm_Value100000171127 = "100000171127" // Lyophilisate and solvent for oral suspension: 
	CombinedDoseForm_Value100000171193 = "100000171193" // Concentrate and solvent for concentrate for oral spray, suspension: 
	CombinedDoseForm_Value100000171238 = "100000171238" // Lyophilisate and solvent for oculonasal suspension: 
	CombinedDoseForm_Value100000171935 = "100000171935" // Emulsion and lyophilisate for suspension for injection: 
	CombinedDoseForm_Value100000174065 = "100000174065" // Powder and solvent for syrup: 
	CombinedDoseForm_Value200000002161 = "200000002161" // Nasal spray, lyophilisate and solvent for suspension: 
	CombinedDoseForm_Value200000002287 = "200000002287" // Powder and solution for bee-hive dispersion: 
	CombinedDoseForm_Value200000004201 = "200000004201" // Solution and dispersion for nebuliser dispersion: 
	CombinedDoseForm_Value200000004819 = "200000004819" // Effervescent powder and powder for oral suspension: 
	CombinedDoseForm_Value200000004820 = "200000004820" // Lyophilisate and solvent for emulsion for injection: 
	CombinedDoseForm_Value200000005547 = "200000005547" // Powder and solution for suspension for injection: 
	CombinedDoseForm_Value200000010382 = "200000010382" // Lyophilisate and solvent for suspension for nasal spray or injection: 
)

// Clone creates a deep copy of the enum
func (e CombinedDoseForm) Clone() *CombinedDoseForm {
	return &CombinedDoseForm{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *CombinedDoseForm) Equals(other *CombinedDoseForm) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

