// Code generated by FHIR Generator. DO NOT EDIT.
// Unified Code for Units of Measure (UCUM). This value set includes all UCUM codes
package fhir_r4b_go
// CommonUCUMCodesForDuration represents the FHIR ValueSet as an enumeration
type CommonUCUMCodesForDuration struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	CommonUCUMCodesForDuration_Ms = "ms" // milliseconds: 
	CommonUCUMCodesForDuration_S = "s" // seconds: 
	CommonUCUMCodesForDuration_Min = "min" // minutes: 
	CommonUCUMCodesForDuration_H = "h" // hours: 
	CommonUCUMCodesForDuration_D = "d" // days: 
	CommonUCUMCodesForDuration_Wk = "wk" // weeks: 
	CommonUCUMCodesForDuration_Mo = "mo" // months: 
	CommonUCUMCodesForDuration_A = "a" // years: 
)

// Clone creates a deep copy of the enum
func (e CommonUCUMCodesForDuration) Clone() *CommonUCUMCodesForDuration {
	return &CommonUCUMCodesForDuration{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *CommonUCUMCodesForDuration) Equals(other *CommonUCUMCodesForDuration) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

