// Code generated by FHIR Generator. DO NOT EDIT.
// Defines which action to take if there is no match in the group.
package fhir_r4b_go
// ConceptMapGroupUnmappedMode represents the FHIR ValueSet as an enumeration
type ConceptMapGroupUnmappedMode struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	ConceptMapGroupUnmappedMode_Provided = "provided" // Provided Code: Use the code as provided in the $translate request.
	ConceptMapGroupUnmappedMode_Fixed = "fixed" // Fixed Code: Use the code explicitly provided in the group.unmapped.
	ConceptMapGroupUnmappedMode_Other_map = "other-map" // Other Map: Use the map identified by the canonical URL in the url element.
)

// Clone creates a deep copy of the enum
func (e ConceptMapGroupUnmappedMode) Clone() *ConceptMapGroupUnmappedMode {
	return &ConceptMapGroupUnmappedMode{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *ConceptMapGroupUnmappedMode) Equals(other *ConceptMapGroupUnmappedMode) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

