// Code generated by FHIR Generator. DO NOT EDIT.
// Used to code the format of the display string.
package fhir_r4b_go

// ContributorRole represents the FHIR ValueSet as an enumeration
type ContributorRole int

const (
	// Publisher: Entity that makes the content available for public use
	ContributorRole_Publisher ContributorRole = iota
	// Author/Creator: An entity primarily responsible for making the resource, often called author or creator
	ContributorRole_Author ContributorRole = iota
	// Reviewer: Entity that examines the content, formally or informally, and suggests revisions or comments
	ContributorRole_Reviewer ContributorRole = iota
	// Endorser: Entity that supports, approves, or advocates for the content
	ContributorRole_Endorser ContributorRole = iota
	// Editor: Entity that revises or has authority to control the content
	ContributorRole_Editor ContributorRole = iota
	// Informant: Entity that supplies information
	ContributorRole_Informant ContributorRole = iota
	// Funder: Entity that supplies financial support
	ContributorRole_Funder ContributorRole = iota
)

// String converts the enum to its string representation
func (e ContributorRole) String() string {
	switch e {
	case ContributorRole_Publisher: return "Publisher"
	case ContributorRole_Author: return "Author/Creator"
	case ContributorRole_Reviewer: return "Reviewer"
	case ContributorRole_Endorser: return "Endorser"
	case ContributorRole_Editor: return "Editor"
	case ContributorRole_Informant: return "Informant"
	case ContributorRole_Funder: return "Funder"
	default: return "Unknown"
	}
}

