// Code generated by FHIR Generator. DO NOT EDIT.
// This value set has asset availability codes.
package fhir_r4b_go

// ContractResourceAssetAvailiabilityCodes represents the FHIR ValueSet as an enumeration
type ContractResourceAssetAvailiabilityCodes int

const (
	// Lease: To be completed
	ContractResourceAssetAvailiabilityCodes_Lease ContractResourceAssetAvailiabilityCodes = iota
)

// String converts the enum to its string representation
func (e ContractResourceAssetAvailiabilityCodes) String() string {
	switch e {
	case ContractResourceAssetAvailiabilityCodes_Lease: return "Lease"
	default: return "Unknown"
	}
}

