// Code generated by FHIR Generator. DO NOT EDIT.
// This value set includes sample Coverage Copayment Type codes.
package fhir_r4b_go

// CoverageCopayTypeCodes represents the FHIR ValueSet as an enumeration
type CoverageCopayTypeCodes int

const (
	// GP Office Visit: An office visit for a general practitioner of a discipline.
	CoverageCopayTypeCodes_Gpvisit CoverageCopayTypeCodes = iota
	// Specialist Office Visit: An office visit for a specialist practitioner of a discipline
	CoverageCopayTypeCodes_Spvisit CoverageCopayTypeCodes = iota
	// Emergency: An episode in an emergency department.
	CoverageCopayTypeCodes_Emergency CoverageCopayTypeCodes = iota
	// Inpatient Hospital: An episode of an Inpatient hospital stay.
	CoverageCopayTypeCodes_Inpthosp CoverageCopayTypeCodes = iota
	// Tele-visit: A visit held where the patient is remote relative to the practitioner, e.g. by phone, computer or video conference.
	CoverageCopayTypeCodes_Televisit CoverageCopayTypeCodes = iota
	// Urgent Care: A visit to an urgent care facility - typically a community care clinic.
	CoverageCopayTypeCodes_Urgentcare CoverageCopayTypeCodes = iota
	// Copay Percentage: A standard percentage applied to all classes or service or product not otherwise specified.
	CoverageCopayTypeCodes_Copaypct CoverageCopayTypeCodes = iota
	// Copay Amount: A standard fixed currency amount applied to all classes or service or product not otherwise specified.
	CoverageCopayTypeCodes_Copay CoverageCopayTypeCodes = iota
	// Deductible: The accumulated amount of patient payment before the coverage begins to pay for services.
	CoverageCopayTypeCodes_Deductible CoverageCopayTypeCodes = iota
	// Maximum out of pocket: The maximum amout of payment for services which a patient, or family, is expected to incur - typically annually.
	CoverageCopayTypeCodes_Maxoutofpocket CoverageCopayTypeCodes = iota
)

// String converts the enum to its string representation
func (e CoverageCopayTypeCodes) String() string {
	switch e {
	case CoverageCopayTypeCodes_Gpvisit: return "GP Office Visit"
	case CoverageCopayTypeCodes_Spvisit: return "Specialist Office Visit"
	case CoverageCopayTypeCodes_Emergency: return "Emergency"
	case CoverageCopayTypeCodes_Inpthosp: return "Inpatient Hospital"
	case CoverageCopayTypeCodes_Televisit: return "Tele-visit"
	case CoverageCopayTypeCodes_Urgentcare: return "Urgent Care"
	case CoverageCopayTypeCodes_Copaypct: return "Copay Percentage"
	case CoverageCopayTypeCodes_Copay: return "Copay Amount"
	case CoverageCopayTypeCodes_Deductible: return "Deductible"
	case CoverageCopayTypeCodes_Maxoutofpocket: return "Maximum out of pocket"
	default: return "Unknown"
	}
}

