// Code generated by FHIR Generator. DO NOT EDIT.
// High-level categorization of the definition, used for searching, sorting, and filtering.
package fhir_r4b_go
// DefinitionTopic represents the FHIR ValueSet as an enumeration
type DefinitionTopic struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	DefinitionTopic_Treatment = "treatment" // Treatment: The definition is related to treatment of the patient.
	DefinitionTopic_Education = "education" // Education: The definition is related to education of the patient.
	DefinitionTopic_Assessment = "assessment" // Assessment: The definition is related to assessment of the patient.
)

// Clone creates a deep copy of the enum
func (e DefinitionTopic) Clone() *DefinitionTopic {
	return &DefinitionTopic{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *DefinitionTopic) Equals(other *DefinitionTopic) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

