// Code generated by FHIR Generator. DO NOT EDIT.
// Indicates the potential degree of impact of the identified issue on the patient.
package fhir_r4b_go
// DetectedIssueSeverity represents the FHIR ValueSet as an enumeration
type DetectedIssueSeverity struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	DetectedIssueSeverity_High = "high" // High: Indicates the issue may be life-threatening or has the potential to cause permanent injury.
	DetectedIssueSeverity_Moderate = "moderate" // Moderate: Indicates the issue may result in noticeable adverse consequences but is unlikely to be life-threatening or cause permanent injury.
	DetectedIssueSeverity_Low = "low" // Low: Indicates the issue may result in some adverse consequences but is unlikely to substantially affect the situation of the subject.
)

// Clone creates a deep copy of the enum
func (e DetectedIssueSeverity) Clone() *DetectedIssueSeverity {
	return &DetectedIssueSeverity{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *DetectedIssueSeverity) Equals(other *DetectedIssueSeverity) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

