// Code generated by FHIR Generator. DO NOT EDIT.
// The media type of the expression language.
package fhir_r4b_go

// ExpressionLanguage represents the FHIR ValueSet as an enumeration
type ExpressionLanguage int

const (
	// CQL: Clinical Quality Language.
	ExpressionLanguage_Text_cql ExpressionLanguage = iota
	// FHIRPath: FHIRPath.
	ExpressionLanguage_Text_fhirpath ExpressionLanguage = iota
	// FHIR Query: FHIR's RESTful query syntax - typically independent of base URL.
	ExpressionLanguage_Application_x_fhir_query ExpressionLanguage = iota
	// CQL Identifier: A valid Clinical Quality Language identifier.
	ExpressionLanguage_Text_cql_identifier ExpressionLanguage = iota
	// CQL Expression: A Clinical Quality Language expression.
	ExpressionLanguage_Text_cql_expression ExpressionLanguage = iota
)

// String converts the enum to its string representation
func (e ExpressionLanguage) String() string {
	switch e {
	case ExpressionLanguage_Text_cql: return "CQL"
	case ExpressionLanguage_Text_fhirpath: return "FHIRPath"
	case ExpressionLanguage_Application_x_fhir_query: return "FHIR Query"
	case ExpressionLanguage_Text_cql_identifier: return "CQL Identifier"
	case ExpressionLanguage_Text_cql_expression: return "CQL Expression"
	default: return "Unknown"
	}
}

