// Code generated by FHIR Generator. DO NOT EDIT.
// The media type of the expression language.
package fhir_r4b_go
// ExpressionLanguage represents the FHIR ValueSet as an enumeration
type ExpressionLanguage struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	ExpressionLanguage_Text_cql = "text/cql" // CQL: Clinical Quality Language.
	ExpressionLanguage_Text_fhirpath = "text/fhirpath" // FHIRPath: FHIRPath.
	ExpressionLanguage_Application_x_fhir_query = "application/x-fhir-query" // FHIR Query: FHIR's RESTful query syntax - typically independent of base URL.
	ExpressionLanguage_Text_cql_identifier = "text/cql-identifier" // CQL Identifier: A valid Clinical Quality Language identifier.
	ExpressionLanguage_Text_cql_expression = "text/cql-expression" // CQL Expression: A Clinical Quality Language expression.
)

// Clone creates a deep copy of the enum
func (e ExpressionLanguage) Clone() *ExpressionLanguage {
	return &ExpressionLanguage{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *ExpressionLanguage) Equals(other *ExpressionLanguage) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

