// Code generated by FHIR Generator. DO NOT EDIT.
// All published FHIR Versions.
package fhir_r4b_go

// FHIRVersion represents the FHIR ValueSet as an enumeration
type FHIRVersion int

const (
	// 0.01: Oldest archived version of FHIR.
	FHIRVersion_Value0_01 FHIRVersion = iota
	// 0.05: 1st Draft for Comment (Sept 2012 Ballot).
	FHIRVersion_Value0_05 FHIRVersion = iota
	// 0.06: 2nd Draft for Comment (January 2013 Ballot).
	FHIRVersion_Value0_06 FHIRVersion = iota
	// 0.11: DSTU 1 Ballot version.
	FHIRVersion_Value0_11 FHIRVersion = iota
	// 0.0.80: DSTU 1 Official version.
	FHIRVersion_Value0_0_80 FHIRVersion = iota
	// 0.0.81: DSTU 1 Official version Technical Errata #1.
	FHIRVersion_Value0_0_81 FHIRVersion = iota
	// 0.0.82: DSTU 1 Official version Technical Errata #2.
	FHIRVersion_Value0_0_82 FHIRVersion = iota
	// 0.4.0: Draft For Comment (January 2015 Ballot).
	FHIRVersion_Value0_4_0 FHIRVersion = iota
	// 0.5.0: DSTU 2 Ballot version (May 2015 Ballot).
	FHIRVersion_Value0_5_0 FHIRVersion = iota
	// 1.0.0: DSTU 2 QA Preview + CQIF Ballot (Sep 2015).
	FHIRVersion_Value1_0_0 FHIRVersion = iota
	// 1.0.1: DSTU 2 (Official version).
	FHIRVersion_Value1_0_1 FHIRVersion = iota
	// 1.0.2: DSTU 2 (Official version) with 1 technical errata.
	FHIRVersion_Value1_0_2 FHIRVersion = iota
	// 1.1.0: GAO Ballot + draft changes to main FHIR standard.
	FHIRVersion_Value1_1_0 FHIRVersion = iota
	// 1.4.0: CQF on FHIR Ballot + Connectathon 12 (Montreal).
	FHIRVersion_Value1_4_0 FHIRVersion = iota
	// 1.6.0: FHIR STU3 Ballot + Connectathon 13 (Baltimore).
	FHIRVersion_Value1_6_0 FHIRVersion = iota
	// 1.8.0: FHIR STU3 Candidate + Connectathon 14 (San Antonio).
	FHIRVersion_Value1_8_0 FHIRVersion = iota
	// 3.0.0: FHIR Release 3 (STU).
	FHIRVersion_Value3_0_0 FHIRVersion = iota
	// 3.0.1: FHIR Release 3 (STU) with 1 technical errata.
	FHIRVersion_Value3_0_1 FHIRVersion = iota
	// 3.0.2: FHIR Release 3 (STU) with 2 technical errata.
	FHIRVersion_Value3_0_2 FHIRVersion = iota
	// 3.3.0: R4 Ballot #1.
	FHIRVersion_Value3_3_0 FHIRVersion = iota
	// 3.5.0: R4 Ballot #2.
	FHIRVersion_Value3_5_0 FHIRVersion = iota
	// 4.0.0: FHIR Release 4 (Normative + STU).
	FHIRVersion_Value4_0_0 FHIRVersion = iota
	// 4.0.1: FHIR Release 4 Technical Correction.
	FHIRVersion_Value4_0_1 FHIRVersion = iota
	// 4.1.0: FHIR Release 4B Ballot #1.
	FHIRVersion_Value4_1_0 FHIRVersion = iota
	// 4.3.0-cibuild: FHIR Release 4B CI-Build.
	FHIRVersion_Value4_3_0_cibuild FHIRVersion = iota
	// 4.3.0-snapshot1: FHIR Release 4B Snapshot #1.
	FHIRVersion_Value4_3_0_snapshot1 FHIRVersion = iota
	// 4.3.0: FHIR Release 4B.
	FHIRVersion_Value4_3_0 FHIRVersion = iota
)

// String converts the enum to its string representation
func (e FHIRVersion) String() string {
	switch e {
	case FHIRVersion_Value0_01: return "0.01"
	case FHIRVersion_Value0_05: return "0.05"
	case FHIRVersion_Value0_06: return "0.06"
	case FHIRVersion_Value0_11: return "0.11"
	case FHIRVersion_Value0_0_80: return "0.0.80"
	case FHIRVersion_Value0_0_81: return "0.0.81"
	case FHIRVersion_Value0_0_82: return "0.0.82"
	case FHIRVersion_Value0_4_0: return "0.4.0"
	case FHIRVersion_Value0_5_0: return "0.5.0"
	case FHIRVersion_Value1_0_0: return "1.0.0"
	case FHIRVersion_Value1_0_1: return "1.0.1"
	case FHIRVersion_Value1_0_2: return "1.0.2"
	case FHIRVersion_Value1_1_0: return "1.1.0"
	case FHIRVersion_Value1_4_0: return "1.4.0"
	case FHIRVersion_Value1_6_0: return "1.6.0"
	case FHIRVersion_Value1_8_0: return "1.8.0"
	case FHIRVersion_Value3_0_0: return "3.0.0"
	case FHIRVersion_Value3_0_1: return "3.0.1"
	case FHIRVersion_Value3_0_2: return "3.0.2"
	case FHIRVersion_Value3_3_0: return "3.3.0"
	case FHIRVersion_Value3_5_0: return "3.5.0"
	case FHIRVersion_Value4_0_0: return "4.0.0"
	case FHIRVersion_Value4_0_1: return "4.0.1"
	case FHIRVersion_Value4_1_0: return "4.1.0"
	case FHIRVersion_Value4_3_0_cibuild: return "4.3.0-cibuild"
	case FHIRVersion_Value4_3_0_snapshot1: return "4.3.0-snapshot1"
	case FHIRVersion_Value4_3_0: return "4.3.0"
	default: return "Unknown"
	}
}

