// Code generated by FHIR Generator. DO NOT EDIT.
// Example list of general categories for flagged issues. (Not complete or necessarily appropriate.)
package fhir_r4b_go
// FlagCategory represents the FHIR ValueSet as an enumeration
type FlagCategory struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	FlagCategory_Diet = "diet" // Diet: Flags related to the subject's dietary needs.
	FlagCategory_Drug = "drug" // Drug: Flags related to the subject's medications.
	FlagCategory_Lab = "lab" // Lab: Flags related to performing laboratory tests and related processes (e.g. phlebotomy).
	FlagCategory_Admin = "admin" // Administrative: Flags related to administrative and financial processes.
	FlagCategory_Contact = "contact" // Subject Contact: Flags related to coming into contact with the patient.
	FlagCategory_Clinical = "clinical" // Clinical: Flags related to the subject's clinical data.
	FlagCategory_Behavioral = "behavioral" // Behavioral: Flags related to behavior.
	FlagCategory_Research = "research" // Research: Flags related to research.
	FlagCategory_Advance_directive = "advance-directive" // Advance Directive: Flags related to subject's advance directives.
	FlagCategory_Safety = "safety" // Safety: Flags related to safety precautions.
)

// Clone creates a deep copy of the enum
func (e FlagCategory) Clone() *FlagCategory {
	return &FlagCategory{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *FlagCategory) Equals(other *FlagCategory) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

