// Code generated by FHIR Generator. DO NOT EDIT.
// Types of resources that are part of group.
package fhir_r4b_go
// GroupType represents the FHIR ValueSet as an enumeration
type GroupType struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	GroupType_Person = "person" // Person: Group contains "person" Patient resources.
	GroupType_Animal = "animal" // Animal: Group contains "animal" Patient resources.
	GroupType_Practitioner = "practitioner" // Practitioner: Group contains healthcare practitioner resources (Practitioner or PractitionerRole).
	GroupType_Device = "device" // Device: Group contains Device resources.
	GroupType_Medication = "medication" // Medication: Group contains Medication resources.
	GroupType_Substance = "substance" // Substance: Group contains Substance resources.
)

// Clone creates a deep copy of the enum
func (e GroupType) Clone() *GroupType {
	return &GroupType{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *GroupType) Equals(other *GroupType) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

