// Code generated by FHIR Generator. DO NOT EDIT.
// The value set to instantiate this attribute should be drawn from a terminologically robust code system that consists of or contains concepts to support describing the reason why a dose is considered to be subpotent. This value set is provided as a suggestive example.
package fhir_r4b_go

// ImmunizationSubpotentReason represents the FHIR ValueSet as an enumeration
type ImmunizationSubpotentReason int

const (
	// Partial Dose: The full volume of the dose was not administered to the patient.
	ImmunizationSubpotentReason_Partial ImmunizationSubpotentReason = iota
	// Cold Chain Break: The vaccine experienced a cold chain break.
	ImmunizationSubpotentReason_Coldchainbreak ImmunizationSubpotentReason = iota
	// Manufacturer Recall: The vaccine was recalled by the manufacturer.
	ImmunizationSubpotentReason_Recall ImmunizationSubpotentReason = iota
)

// String converts the enum to its string representation
func (e ImmunizationSubpotentReason) String() string {
	switch e {
	case ImmunizationSubpotentReason_Partial: return "Partial Dose"
	case ImmunizationSubpotentReason_Coldchainbreak: return "Cold Chain Break"
	case ImmunizationSubpotentReason_Recall: return "Manufacturer Recall"
	default: return "Unknown"
	}
}

