// Code generated by FHIR Generator. DO NOT EDIT.
// Laterality: SNOMED-CT concepts for 'left', 'right', and 'bilateral'
package fhir_r4b_go

// Laterality represents the FHIR ValueSet as an enumeration
type Laterality int

const (
	// Unilateral left: 
	Laterality_Value419161000 Laterality = iota
	// Unilateral right: 
	Laterality_Value419465000 Laterality = iota
	// Bilateral: 
	Laterality_Value51440002 Laterality = iota
)

// String converts the enum to its string representation
func (e Laterality) String() string {
	switch e {
	case Laterality_Value419161000: return "Unilateral left"
	case Laterality_Value419465000: return "Unilateral right"
	case Laterality_Value51440002: return "Bilateral"
	default: return "Unknown"
	}
}

