// Code generated by FHIR Generator. DO NOT EDIT.
// This value set defines the set of codes that can be used to indicate the marital status of a person.
package fhir_r4b_go

// MaritalStatusCodes represents the FHIR ValueSet as an enumeration
type MaritalStatusCodes int

const (
	// : 
	MaritalStatusCodes_UNK MaritalStatusCodes = iota
)

// String converts the enum to its string representation
func (e MaritalStatusCodes) String() string {
	switch e {
	case MaritalStatusCodes_UNK: return ""
	default: return "Unknown"
	}
}

