// Code generated by FHIR Generator. DO NOT EDIT.
// MedicationRequest Category Codes
package fhir_r4b_go

// MedicationRequestCategoryCodes represents the FHIR ValueSet as an enumeration
type MedicationRequestCategoryCodes int

const (
	// Inpatient: Includes requests for medications to be administered or consumed in an inpatient or acute care setting
	MedicationRequestCategoryCodes_Inpatient MedicationRequestCategoryCodes = iota
	// Outpatient: Includes requests for medications to be administered or consumed in an outpatient setting (for example, Emergency Department, Outpatient Clinic, Outpatient Surgery, Doctor's office)
	MedicationRequestCategoryCodes_Outpatient MedicationRequestCategoryCodes = iota
	// Community: Includes requests for medications to be administered or consumed by the patient in their home (this would include long term care or nursing homes, hospices, etc.)
	MedicationRequestCategoryCodes_Community MedicationRequestCategoryCodes = iota
	// Discharge: Includes requests for medications created when the patient is being released from a facility
	MedicationRequestCategoryCodes_Discharge MedicationRequestCategoryCodes = iota
)

// String converts the enum to its string representation
func (e MedicationRequestCategoryCodes) String() string {
	switch e {
	case MedicationRequestCategoryCodes_Inpatient: return "Inpatient"
	case MedicationRequestCategoryCodes_Outpatient: return "Outpatient"
	case MedicationRequestCategoryCodes_Community: return "Community"
	case MedicationRequestCategoryCodes_Discharge: return "Discharge"
	default: return "Unknown"
	}
}

