// Code generated by FHIR Generator. DO NOT EDIT.
// Codes identifying the lifecycle stage of a product.
package fhir_r4b_go
// NutritionProductStatus represents the FHIR ValueSet as an enumeration
type NutritionProductStatus struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	NutritionProductStatus_Active = "active" // Active: The product can be used.
	NutritionProductStatus_Inactive = "inactive" // Inactive: The product is not expected or allowed to be used.
	NutritionProductStatus_Entered_in_error = "entered-in-error" // Entered in Error: This electronic record should never have existed, though it is possible that real-world decisions were based on it. (If real-world activity has occurred, the status should be "cancelled" rather than "entered-in-error".).
)

// Clone creates a deep copy of the enum
func (e NutritionProductStatus) Clone() *NutritionProductStatus {
	return &NutritionProductStatus{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *NutritionProductStatus) Equals(other *NutritionProductStatus) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

