// Code generated by FHIR Generator. DO NOT EDIT.
// This value set defines a set of codes that can be used to indicate the particular target population the reference range applies to.
package fhir_r4b_go

// ObservationReferenceRangeAppliesToCodes represents the FHIR ValueSet as an enumeration
type ObservationReferenceRangeAppliesToCodes int

const (
	// : 
	ObservationReferenceRangeAppliesToCodes_Value248153007 ObservationReferenceRangeAppliesToCodes = iota
	// : 
	ObservationReferenceRangeAppliesToCodes_Value248152002 ObservationReferenceRangeAppliesToCodes = iota
	// : 
	ObservationReferenceRangeAppliesToCodes_Value77386006 ObservationReferenceRangeAppliesToCodes = iota
)

// String converts the enum to its string representation
func (e ObservationReferenceRangeAppliesToCodes) String() string {
	switch e {
	case ObservationReferenceRangeAppliesToCodes_Value248153007: return ""
	case ObservationReferenceRangeAppliesToCodes_Value248152002: return ""
	case ObservationReferenceRangeAppliesToCodes_Value77386006: return ""
	default: return "Unknown"
	}
}

