// Code generated by FHIR Generator. DO NOT EDIT.
// Extra measures defined for a Medicinal Product, such as heightened reporting requirements.
package fhir_r4b_go

// PediatricUse represents the FHIR ValueSet as an enumeration
type PediatricUse int

const (
	// In utero: In utero
	PediatricUse_InUtero PediatricUse = iota
	// Preterm newborn infants (0 – 27 days): Preterm newborn infants (0 – 27 days)
	PediatricUse_PretermNewborn PediatricUse = iota
	// Term newborn infants (0 – 27 days): Term newborn infants (0 – 27 days)
	PediatricUse_TermNewborn PediatricUse = iota
	// Infants and toddlers (28 days – 23 months): Infants and toddlers (28 days – 23 months)
	PediatricUse_Infants PediatricUse = iota
	// Children (2 to < 12 years): Children (2 to < 12 years)
	PediatricUse_Children PediatricUse = iota
	// Adolescents (12 to < 18 years): Adolescents (12 to < 18 years)
	PediatricUse_Adolescents PediatricUse = iota
	// Adults (18 to < 65 years): Adults (18 to < 65 years)
	PediatricUse_Adults PediatricUse = iota
	// Elderly (≥ 65 years): Elderly (≥ 65 years)
	PediatricUse_Elderly PediatricUse = iota
	// Neonate: Neonate
	PediatricUse_Neonate PediatricUse = iota
	// Pediatric Population (< 18 years): Pediatric Population (< 18 years)
	PediatricUse_PediatricPopulation PediatricUse = iota
	// All: All
	PediatricUse_All PediatricUse = iota
	// Prepubertal children (2 years to onset of puberty): Prepubertal children (2 years to onset of puberty)
	PediatricUse_Prepubertal PediatricUse = iota
	// Adult and elderly population (> 18 years): Adult and elderly population (> 18 years)
	PediatricUse_AdultsAndElderly PediatricUse = iota
	// Pubertal and postpubertal adolescents (onset of puberty to < 18 years): Pubertal and postpubertal adolescents (onset of puberty to < 18 years)
	PediatricUse_PubertalAndPostpubertal PediatricUse = iota
)

// String converts the enum to its string representation
func (e PediatricUse) String() string {
	switch e {
	case PediatricUse_InUtero: return "In utero"
	case PediatricUse_PretermNewborn: return "Preterm newborn infants (0 – 27 days)"
	case PediatricUse_TermNewborn: return "Term newborn infants (0 – 27 days)"
	case PediatricUse_Infants: return "Infants and toddlers (28 days – 23 months)"
	case PediatricUse_Children: return "Children (2 to < 12 years)"
	case PediatricUse_Adolescents: return "Adolescents (12 to < 18 years)"
	case PediatricUse_Adults: return "Adults (18 to < 65 years)"
	case PediatricUse_Elderly: return "Elderly (≥ 65 years)"
	case PediatricUse_Neonate: return "Neonate"
	case PediatricUse_PediatricPopulation: return "Pediatric Population (< 18 years)"
	case PediatricUse_All: return "All"
	case PediatricUse_Prepubertal: return "Prepubertal children (2 years to onset of puberty)"
	case PediatricUse_AdultsAndElderly: return "Adult and elderly population (> 18 years)"
	case PediatricUse_PubertalAndPostpubertal: return "Pubertal and postpubertal adolescents (onset of puberty to < 18 years)"
	default: return "Unknown"
	}
}

