// Code generated by FHIR Generator. DO NOT EDIT.
// Procedure Outcome code: A selection of relevant SNOMED CT codes.
package fhir_r4b_go
// ProcedureOutcomeCodesSNOMEDCT represents the FHIR ValueSet as an enumeration
type ProcedureOutcomeCodesSNOMEDCT struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	ProcedureOutcomeCodesSNOMEDCT_Value385669000 = "385669000" // : 
	ProcedureOutcomeCodesSNOMEDCT_Value385671000 = "385671000" // : 
	ProcedureOutcomeCodesSNOMEDCT_Value385670004 = "385670004" // : 
)

// Clone creates a deep copy of the enum
func (e ProcedureOutcomeCodesSNOMEDCT) Clone() *ProcedureOutcomeCodesSNOMEDCT {
	return &ProcedureOutcomeCodesSNOMEDCT{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *ProcedureOutcomeCodesSNOMEDCT) Equals(other *ProcedureOutcomeCodesSNOMEDCT) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

