// Code generated by FHIR Generator. DO NOT EDIT.
// This value set contains representative Activity Type codes, which includes codes from the HL7 DocumentCompletion, ActStatus, and DataOperations code system, W3C PROV-DM and PROV-N concepts and display names, several HL7 Lifecycle Event codes for which there are agreed upon definitions, and non-duplicated codes from the HL7 Security and Privacy Ontology Operations codes.
package fhir_r4b_go

// ProvenanceActivityType represents the FHIR ValueSet as an enumeration
type ProvenanceActivityType int

const (
	// : 
	ProvenanceActivityType_LA ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_ANONY ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_DEID ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_MASK ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_LABEL ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_PSEUD ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_CREATE ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_DELETE ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_UPDATE ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_APPEND ProvenanceActivityType = iota
	// : 
	ProvenanceActivityType_NULLIFY ProvenanceActivityType = iota
)

// String converts the enum to its string representation
func (e ProvenanceActivityType) String() string {
	switch e {
	case ProvenanceActivityType_LA: return ""
	case ProvenanceActivityType_ANONY: return ""
	case ProvenanceActivityType_DEID: return ""
	case ProvenanceActivityType_MASK: return ""
	case ProvenanceActivityType_LABEL: return ""
	case ProvenanceActivityType_PSEUD: return ""
	case ProvenanceActivityType_CREATE: return ""
	case ProvenanceActivityType_DELETE: return ""
	case ProvenanceActivityType_UPDATE: return ""
	case ProvenanceActivityType_APPEND: return ""
	case ProvenanceActivityType_NULLIFY: return ""
	default: return "Unknown"
	}
}

