// Code generated by FHIR Generator. DO NOT EDIT.
// The type of publication such as book, database, or journal.
package fhir_r4b_go
// PublishedInType represents the FHIR ValueSet as an enumeration
type PublishedInType struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	PublishedInType_D020492 = "D020492" // Periodical: Publication intended to be issued on an ongoing basis, generally more frequently than annually, containing separate articles, stories, or writings.
	PublishedInType_D019991 = "D019991" // Database: A structured file of information or a set of logically related data stored and retrieved using computer-based means.
	PublishedInType_D001877 = "D001877" // Book: Non-periodical written or printed works consisting of sheets of pages fastened or bound together within covers.
	PublishedInType_D064886 = "D064886" // Dataset: Works consisting of organized collections of data, which have been stored permanently in a formalized manner suitable for communication, interpretation, or processing.
)

// Clone creates a deep copy of the enum
func (e PublishedInType) Clone() *PublishedInType {
	return &PublishedInType{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *PublishedInType) Equals(other *PublishedInType) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

