// Code generated by FHIR Generator. DO NOT EDIT.
// The outcome of the processing.
package fhir_r4b_go
// RemittanceOutcome represents the FHIR ValueSet as an enumeration
type RemittanceOutcome struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	RemittanceOutcome_Queued = "queued" // Queued: The Claim/Pre-authorization/Pre-determination has been received but processing has not begun.
	RemittanceOutcome_Complete = "complete" // Complete: The processing completed without errors.
	RemittanceOutcome_Error = "error" // Error: The processing identified errors.
	RemittanceOutcome_Partial = "partial" // Partial: No errors have been detected and some of the adjudication has been performed.
)

// Clone creates a deep copy of the enum
func (e RemittanceOutcome) Clone() *RemittanceOutcome {
	return &RemittanceOutcome{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *RemittanceOutcome) Equals(other *RemittanceOutcome) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

