// Code generated by FHIR Generator. DO NOT EDIT.
// The code(s) that detail the conditions under which the healthcare service is available/offered.
package fhir_r4b_go
// ServiceProvisionConditions represents the FHIR ValueSet as an enumeration
type ServiceProvisionConditions struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	ServiceProvisionConditions_Free = "free" // Free: This service is available for no patient cost.
	ServiceProvisionConditions_Disc = "disc" // Discounts Available: There are discounts available on this service for qualifying patients.
	ServiceProvisionConditions_Cost = "cost" // Fees apply: Fees apply for this service.
)

// Clone creates a deep copy of the enum
func (e ServiceProvisionConditions) Clone() *ServiceProvisionConditions {
	return &ServiceProvisionConditions{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *ServiceProvisionConditions) Equals(other *ServiceProvisionConditions) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

