// Code generated by FHIR Generator. DO NOT EDIT.
// If this is the default rule set to apply for the source type, or this combination of types.
package fhir_r4b_go
// StructureMapGroupTypeMode represents the FHIR ValueSet as an enumeration
type StructureMapGroupTypeMode struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	StructureMapGroupTypeMode_None = "none" // Not a Default: This group is not a default group for the types.
	StructureMapGroupTypeMode_Types = "types" // Default for Type Combination: This group is a default mapping group for the specified types and for the primary source type.
	StructureMapGroupTypeMode_Type_and_types = "type-and-types" // Default for type + combination: This group is a default mapping group for the specified types.
)

// Clone creates a deep copy of the enum
func (e StructureMapGroupTypeMode) Clone() *StructureMapGroupTypeMode {
	return &StructureMapGroupTypeMode{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *StructureMapGroupTypeMode) Equals(other *StructureMapGroupTypeMode) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

