// Code generated by FHIR Generator. DO NOT EDIT.
// The status of a subscription.
package fhir_r4b_go
// SubscriptionStatusCodes represents the FHIR ValueSet as an enumeration
type SubscriptionStatusCodes struct {
	Value   *string  `json:"value,omitempty"`
	Element *Element `json:"_value,omitempty"`
}

// Enum constants
const (
	SubscriptionStatusCodes_Requested = "requested" // Requested: The client has requested the subscription, and the server has not yet set it up.
	SubscriptionStatusCodes_Active = "active" // Active: The subscription is active.
	SubscriptionStatusCodes_Error = "error" // Error: The server has an error executing the notification.
	SubscriptionStatusCodes_Off = "off" // Off: Too many errors have occurred or the subscription has expired.
)

// Clone creates a deep copy of the enum
func (e SubscriptionStatusCodes) Clone() *SubscriptionStatusCodes {
	return &SubscriptionStatusCodes{Value: e.Value, Element: e.Element.Clone()}
}

// Equals checks equality between two enums
func (e *SubscriptionStatusCodes) Equals(other *SubscriptionStatusCodes) bool {
	return e.Value == other.Value && e.Element.Equals(other.Element)
}

