// Code generated by FHIR Generator. DO NOT EDIT.
// SupplementType : Codes for nutritional supplements to be provided to the patient. This value set is composed of SNOMED CT (US Extension) Concepts from SCTID 470581016 (Enteral+supplement feeds hierarchy (product)) and is provided as a suggestive example.
package fhir_r4b_go

// SupplementTypeCodes represents the FHIR ValueSet as an enumeration
type SupplementTypeCodes int

const (
	// Adult clear liquid supplement: 
	SupplementTypeCodes_Value442901000124106 SupplementTypeCodes = iota
	// Adult critical care formula: 
	SupplementTypeCodes_Value443031000124106 SupplementTypeCodes = iota
	// Adult diabetes specialty formula: 
	SupplementTypeCodes_Value443051000124104 SupplementTypeCodes = iota
	// Adult elemental formula: 
	SupplementTypeCodes_Value442911000124109 SupplementTypeCodes = iota
	// Adult hepatic specialty formula: 
	SupplementTypeCodes_Value443021000124108 SupplementTypeCodes = iota
	// Adult high energy formula: 
	SupplementTypeCodes_Value442971000124100 SupplementTypeCodes = iota
	// Adult hydrolyzed protein formula: 
	SupplementTypeCodes_Value442981000124102 SupplementTypeCodes = iota
	// Adult high protein formula: 
	SupplementTypeCodes_Value442991000124104 SupplementTypeCodes = iota
	// Adult high protein high fiber formula: 
	SupplementTypeCodes_Value443011000124100 SupplementTypeCodes = iota
	// Adult low carbohydrate formula: 
	SupplementTypeCodes_Value442961000124107 SupplementTypeCodes = iota
	// Adult pulmonary specialty formula: 
	SupplementTypeCodes_Value442951000124105 SupplementTypeCodes = iota
	// Adult renal specialty formula: 
	SupplementTypeCodes_Value442941000124108 SupplementTypeCodes = iota
	// Adult standard formula: 
	SupplementTypeCodes_Value442921000124101 SupplementTypeCodes = iota
	// Adult soy protein isolate formula: 
	SupplementTypeCodes_Value442931000124103 SupplementTypeCodes = iota
	// Diabetic meal replacement bar: 
	SupplementTypeCodes_Value444331000124106 SupplementTypeCodes = iota
	// Pediatric Formula: 
	SupplementTypeCodes_Value443361000124100 SupplementTypeCodes = iota
	// Pediatric clear liquid supplement: 
	SupplementTypeCodes_Value443391000124108 SupplementTypeCodes = iota
	// Pediatric elemental formula: 
	SupplementTypeCodes_Value443401000124105 SupplementTypeCodes = iota
	// Pediatric high energy formula: 
	SupplementTypeCodes_Value443491000124103 SupplementTypeCodes = iota
	// Pediatric high energy formula with increased fiber: 
	SupplementTypeCodes_Value443501000124106 SupplementTypeCodes = iota
	// Pediatric hydrolyzed protein formula: 
	SupplementTypeCodes_Value443421000124100 SupplementTypeCodes = iota
	// Pediatric increased fiber formula: 
	SupplementTypeCodes_Value443471000124104 SupplementTypeCodes = iota
	// Pediatric reduced energy formula: 
	SupplementTypeCodes_Value444431000124104 SupplementTypeCodes = iota
	// Pediatric standard formula: 
	SupplementTypeCodes_Value443451000124109 SupplementTypeCodes = iota
	// Standard pudding oral supplement: 
	SupplementTypeCodes_Value444321000124108 SupplementTypeCodes = iota
	// Standard enteral formula with fiber: 
	SupplementTypeCodes_Value441561000124106 SupplementTypeCodes = iota
	// Standard Formula: 
	SupplementTypeCodes_Value443461000124106 SupplementTypeCodes = iota
	// Standard Enteral Formula: 
	SupplementTypeCodes_Value441531000124102 SupplementTypeCodes = iota
	// Soy based formula: 
	SupplementTypeCodes_Value443561000124107 SupplementTypeCodes = iota
	// Renal Formula: 
	SupplementTypeCodes_Value443481000124101 SupplementTypeCodes = iota
	// High energy enteral formula with fiber: 
	SupplementTypeCodes_Value441571000124104 SupplementTypeCodes = iota
	// Diabetic enteral formula with fiber: 
	SupplementTypeCodes_Value441591000124103 SupplementTypeCodes = iota
	// Diabetic high calorie high protein enteral formula with fiber: 
	SupplementTypeCodes_Value441601000124106 SupplementTypeCodes = iota
	// Increased fiber formula: 
	SupplementTypeCodes_Value443351000124102 SupplementTypeCodes = iota
	// Hydrolyzed protein formula: 
	SupplementTypeCodes_Value443771000124106 SupplementTypeCodes = iota
	// Hydrolyzed peptide-based high protein enteral formula: 
	SupplementTypeCodes_Value441671000124100 SupplementTypeCodes = iota
	// High protein formula: 
	SupplementTypeCodes_Value443111000124101 SupplementTypeCodes = iota
	// High Energy Formula: 
	SupplementTypeCodes_Value443431000124102 SupplementTypeCodes = iota
	// Elemental Formula: 
	SupplementTypeCodes_Value443411000124108 SupplementTypeCodes = iota
	// Electrolyte replacement supplement: 
	SupplementTypeCodes_Value444361000124102 SupplementTypeCodes = iota
	// Frozen electrolyte replacement supplement: 
	SupplementTypeCodes_Value444401000124107 SupplementTypeCodes = iota
	// Liquid electrolyte replacement supplement: 
	SupplementTypeCodes_Value444381000124107 SupplementTypeCodes = iota
	// Powdered electrolyte replacement supplement: 
	SupplementTypeCodes_Value444371000124109 SupplementTypeCodes = iota
	// Clear liquid supplement: 
	SupplementTypeCodes_Value443441000124107 SupplementTypeCodes = iota
	// Adult formula: 
	SupplementTypeCodes_Value442651000124102 SupplementTypeCodes = iota
)

// String converts the enum to its string representation
func (e SupplementTypeCodes) String() string {
	switch e {
	case SupplementTypeCodes_Value442901000124106: return "Adult clear liquid supplement"
	case SupplementTypeCodes_Value443031000124106: return "Adult critical care formula"
	case SupplementTypeCodes_Value443051000124104: return "Adult diabetes specialty formula"
	case SupplementTypeCodes_Value442911000124109: return "Adult elemental formula"
	case SupplementTypeCodes_Value443021000124108: return "Adult hepatic specialty formula"
	case SupplementTypeCodes_Value442971000124100: return "Adult high energy formula"
	case SupplementTypeCodes_Value442981000124102: return "Adult hydrolyzed protein formula"
	case SupplementTypeCodes_Value442991000124104: return "Adult high protein formula"
	case SupplementTypeCodes_Value443011000124100: return "Adult high protein high fiber formula"
	case SupplementTypeCodes_Value442961000124107: return "Adult low carbohydrate formula"
	case SupplementTypeCodes_Value442951000124105: return "Adult pulmonary specialty formula"
	case SupplementTypeCodes_Value442941000124108: return "Adult renal specialty formula"
	case SupplementTypeCodes_Value442921000124101: return "Adult standard formula"
	case SupplementTypeCodes_Value442931000124103: return "Adult soy protein isolate formula"
	case SupplementTypeCodes_Value444331000124106: return "Diabetic meal replacement bar"
	case SupplementTypeCodes_Value443361000124100: return "Pediatric Formula"
	case SupplementTypeCodes_Value443391000124108: return "Pediatric clear liquid supplement"
	case SupplementTypeCodes_Value443401000124105: return "Pediatric elemental formula"
	case SupplementTypeCodes_Value443491000124103: return "Pediatric high energy formula"
	case SupplementTypeCodes_Value443501000124106: return "Pediatric high energy formula with increased fiber"
	case SupplementTypeCodes_Value443421000124100: return "Pediatric hydrolyzed protein formula"
	case SupplementTypeCodes_Value443471000124104: return "Pediatric increased fiber formula"
	case SupplementTypeCodes_Value444431000124104: return "Pediatric reduced energy formula"
	case SupplementTypeCodes_Value443451000124109: return "Pediatric standard formula"
	case SupplementTypeCodes_Value444321000124108: return "Standard pudding oral supplement"
	case SupplementTypeCodes_Value441561000124106: return "Standard enteral formula with fiber"
	case SupplementTypeCodes_Value443461000124106: return "Standard Formula"
	case SupplementTypeCodes_Value441531000124102: return "Standard Enteral Formula"
	case SupplementTypeCodes_Value443561000124107: return "Soy based formula"
	case SupplementTypeCodes_Value443481000124101: return "Renal Formula"
	case SupplementTypeCodes_Value441571000124104: return "High energy enteral formula with fiber"
	case SupplementTypeCodes_Value441591000124103: return "Diabetic enteral formula with fiber"
	case SupplementTypeCodes_Value441601000124106: return "Diabetic high calorie high protein enteral formula with fiber"
	case SupplementTypeCodes_Value443351000124102: return "Increased fiber formula"
	case SupplementTypeCodes_Value443771000124106: return "Hydrolyzed protein formula"
	case SupplementTypeCodes_Value441671000124100: return "Hydrolyzed peptide-based high protein enteral formula"
	case SupplementTypeCodes_Value443111000124101: return "High protein formula"
	case SupplementTypeCodes_Value443431000124102: return "High Energy Formula"
	case SupplementTypeCodes_Value443411000124108: return "Elemental Formula"
	case SupplementTypeCodes_Value444361000124102: return "Electrolyte replacement supplement"
	case SupplementTypeCodes_Value444401000124107: return "Frozen electrolyte replacement supplement"
	case SupplementTypeCodes_Value444381000124107: return "Liquid electrolyte replacement supplement"
	case SupplementTypeCodes_Value444371000124109: return "Powdered electrolyte replacement supplement"
	case SupplementTypeCodes_Value443441000124107: return "Clear liquid supplement"
	case SupplementTypeCodes_Value442651000124102: return "Adult formula"
	default: return "Unknown"
	}
}

