// Code generated by FHIR Generator. DO NOT EDIT.
// The type of trigger.
package fhir_r4b_go

// TriggerType represents the FHIR ValueSet as an enumeration
type TriggerType int

const (
	// Named Event: The trigger occurs in response to a specific named event, and no other information about the trigger is specified. Named events are completely pre-coordinated, and the formal semantics of the trigger are not provided.
	TriggerType_Named_event TriggerType = iota
	// Periodic: The trigger occurs at a specific time or periodically as described by a timing or schedule. A periodic event cannot have any data elements, but may have a name assigned as a shorthand for the event.
	TriggerType_Periodic TriggerType = iota
	// Data Changed: The trigger occurs whenever data of a particular type is changed in any way, either added, modified, or removed.
	TriggerType_Data_changed TriggerType = iota
	// Data Added: The trigger occurs whenever data of a particular type is added.
	TriggerType_Data_added TriggerType = iota
	// Data Updated: The trigger occurs whenever data of a particular type is modified.
	TriggerType_Data_modified TriggerType = iota
	// Data Removed: The trigger occurs whenever data of a particular type is removed.
	TriggerType_Data_removed TriggerType = iota
	// Data Accessed: The trigger occurs whenever data of a particular type is accessed.
	TriggerType_Data_accessed TriggerType = iota
	// Data Access Ended: The trigger occurs whenever access to data of a particular type is completed.
	TriggerType_Data_access_ended TriggerType = iota
)

// String converts the enum to its string representation
func (e TriggerType) String() string {
	switch e {
	case TriggerType_Named_event: return "Named Event"
	case TriggerType_Periodic: return "Periodic"
	case TriggerType_Data_changed: return "Data Changed"
	case TriggerType_Data_added: return "Data Added"
	case TriggerType_Data_modified: return "Data Updated"
	case TriggerType_Data_removed: return "Data Removed"
	case TriggerType_Data_accessed: return "Data Accessed"
	case TriggerType_Data_access_ended: return "Data Access Ended"
	default: return "Unknown"
	}
}

